### PR TITLE
include sshd_config.d to allow overrides

### PR DESCRIPTION
**Pull request by chasebolt**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [X] I have read the [contributing](https://github.com/linuxserver/docker-openssh-server/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
you can not easily override sections of sshd_config without overwriting the entire file. sshd_config has the option `Include` to load in additional configs.

## Benefits of this PR and context:

a user can mount additional configs to be applied to the sshd_config.

### CODE REVIEW

**Comment by aptalca** [comment]
There is no need. `sshd_config` is already in the config folder and is user customizable

**Comment by chasebolt** [comment]
doing that risks breaking functionality that modifies the sshd_config. also
it is preferred to not fully manage the sshd_config, but to just append
Match User settings via include files.

**Comment by aptalca** [comment]
The line you're echo'ing into it, you can just do it manually. No need to add it to the init script

**Comment by Luwdo** [comment]
What I ended up doing was adding a new container init script config map mounted into the image to do the modifications to sshd_config that i wanted.

**Comment by aptalca** [comment]
> What I ended up doing was adding a new container init script config map mounted into the image to do the modifications to sshd_config that i wanted.

That's exactly what I was going to suggest. Alternatively, you can create a docker mod (either official in our repo) or unofficially in your docker repo and just add it to your yaml as an env var:
https://mods.linuxserver.io/

Because to be honest, it's an edge case to want custom internal ports for these containers

**Comment by chasebolt** [comment]
i think this PR is just to make it easier to customize the sshd config settings, without having to fully manage the sshd config. i prefer to use the default config and layer my changes from there.

i don't fully understand why allowing the use of the sshd dynamic include goes against the idea behind this container.

**Comment by aptalca** [comment]
Because some folks want to configure _everything_ via env vars. We have to be the gatekeeper. We don't want our images to support way too many env vars because that confuses most regular users and add a lot more support burden. Oh and the fact that if there is an advertised var, folks will try to edit it and break things. So it goes against KISS.

We add vars that are necessary to get it going and needed by most users. For others, we only consider a var if it's not doable by other means (via editing config files in the config folder).

For changing internal ports, we only do it when it's necessary (like for qbittorrent where the host port needs to match the internal port due to csrf). But if we just allow for it because someone wanted it, there will be tons of users coming to us for support because they changed the internal port, but their port mapping still refers to the default internal port.

In this specific case, you want us to add a specific functionality that is not totally necessary. The config is already in the host mapped config folder. You want the functionality so you can make changes to your config folder. But the functionality already is about making changes to the config folder. Why can't you make both changes at once? Add the include yourself, and then drop whatever config you want into that folder.

**Comment by drizuid** [comment]
Work arounds discussed and PR will not be merged, closing

**Pull request closed without merging**
