### PR TITLE
#30 Added ability to define SSH port from ENV variables (2)

### PR DESCRIPTION
**Pull request by faan11**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [X] I have read the [contributing](https://github.com/linuxserver/docker-openssh-server/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Added ability to define SSH port from ENV variables. This commit is a revised version of #42 and includes an updated readme-vars along with the correct changes in the script.

## Benefits of this PR and context:

As application builder I would like to use another ssh port in container than default hardcoded value 2222.

New environment variable is optional and can be omitted in container configurarion without harm. In this case default port 2222 would be used.

## How Has This Been Tested?

```


docker run -d \
  --name=openssh-server \
  --hostname=openssh-server `#optional` \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e OPENSSH_PORT=1234 `#optional` \
  -e PASSWORD_ACCESS=true `#optional` \
  -e USER_PASSWORD=password `#optional` \
  -e USER_NAME=user `#optional` \
  -p 1234:1234 \
  --restart unless-stopped \
  docker-openssh-server
ssh -p 1234 user@localhost
```

### CODE REVIEW

**Comment by aptalca** [comment]
Thanks for the PR but we don't allow changing the internal port unless it's absolutely necessary like it is for qbittorrent (csrf).

You can map any port you like on the host.

**Comment by IamIpanda** [comment]
Hi I believe we really need it for hack 22 port inner a K8s pod.

This issue has been raised 2 years ago:
https://github.com/linuxserver/docker-openssh-server/issues/30
And the workaround mentioned in don't work for this new version.

Or, is it possible just change this port to 22, people can map to 2222 on the host ?

**Comment by aptalca** [comment]
This is more suitable for a docker mod. There are already a few for this image: https://mods.linuxserver.io/?mod=openssh-server

**Comment by drizuid** [comment]
closing as we will not merge

**Pull request closed without merging**
