### PR TITLE
#30 Added ability to define SSH port from ENV variables

### PR DESCRIPTION
**Pull request by andriyun**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-openssh-server/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Added ability to define SSH port from ENV variables

## Benefits of this PR and context:

As application builder I would like to use another ssh port in container than default hardcoded value `2222`.

New environment variable is optional and can be ommited in container configurarion without harm. In this case default port `2222` would be used.

## How Has This Been Tested?

This change has been tested with following commands:
```
docker run -d \
  --name=openssh-server \
  --hostname=openssh-server `#optional` \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e OPENSSH_PORT=1234 `#optional` \
  -e PASSWORD_ACCESS=true `#optional` \
  -e USER_PASSWORD=password `#optional` \
  -e USER_NAME=user `#optional` \
  -p 1234:1234 \
  --restart unless-stopped \
  docker-openssh-server
ssh -p 1234 user@localhost
```

### CODE REVIEW

**Comment by Roxedus** [comment]
This change also need documentation in the readme-vars.

**Comment by aptalca** [comment]
Thanks for the PR, but `I would like to use another port` is not a good enough justification.

You can already map it to whatever port you like. That's the beauty of docker bridge networking.

**Comment by andriyun** [comment]
Hej @aptalca 
Currently I'm trying to use this image in Kubernetes cluster for ssh service as separate application with exposed port.
There is no need for bridge networking, but there is a need for specific port.

If there a way to run this image with some other environment related configuration that allows me setup the port I need?

**Comment by andriyun** [comment]
@Roxedus 
> This change also need documentation in the readme-vars.

I wanted to, really.
But I read first line in README.md file https://github.com/linuxserver/docker-openssh-server/blob/master/README.md
```
<!-- DO NOT EDIT THIS FILE MANUALLY  -->
```
And decided to get approved major changes  :-D

**Comment by Roxedus** [comment]
It links you to the document telling you how to edit the readme-vars

**Comment by aptalca** [comment]
I mean, you can probably handle that through your ingress and such. In any case, if you really want to customize it, see here: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by andriyun** [comment]
Ok. Thx for response
I'll check what I can do.

**Comment by jj-uk** [comment]
If  `-p ${OPENSSH_PORT}` was changed to `${OPENSSH_PORT_STRING}` (remove the -p), the user then has the ability to open multiple ports, e.g.

`'OPENSSH_PORT_STRING'='-p 2221 -p 2222 -p 2223'`


Contents of /etc/services.d/openssh-server/run
```
#!/usr/bin/with-contenv bash

USER_NAME=${USER_NAME:-linuxserver.io}
OPENSSH_PORT_STRING=${OPENSSH_PORT_STRING:--p 2222}

exec 2>&1 \
        s6-setuidgid ${USER_NAME} /usr/sbin/sshd -D -e ${OPENSSH_PORT_STRING}
```

I need this to use this docker as a relay for reverse ssh.

**Comment by KyleKotowick** [comment]
@aptalca @Roxedus Any chance we can get this merged? It seems unnecessary since you can normally map ports as desired, but when using AWS ECS with VPC networking, you can only map ports to themselves (container port must match the host port). This makes it impossible to use anything other than 2222 since that value is hardcoded.

**Comment by Roxedus** [comment]
> @aptalca @Roxedus Any chance we can get this merged? It seems unnecessary since you can normally map ports as desired, but when using AWS ECS with VPC networking, you can only map ports to themselves (container port must match the host port). This makes it impossible to use anything other than 2222 since that value is hardcoded.

Wont get merged until the requested changes are done by the submitter.

**Comment by Luwdo** [comment]
I will work on a new PR for this feature for both this and for https://github.com/linuxserver/docker-endlessh as if you are deploying these into a kubernetes cluster within the same pod, container ports cannot conflict.

Without the ability to change the container port it requires you to either run multiple services or multiple pods which is suboptimum if you have a number of ssh services you are running in the same pod and you want to scale them together.

Especially if you are pairing each service with an endless ssh and an open ssh.

**Pull request closed without merging**
