### PR TITLE
Support for scp by installing openssh-client package

### PR DESCRIPTION
**Pull request by vladimirvivien**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

 

------------------------------

We welcome all PR’s though this doesn’t guarantee it will be accepted.

## Description:

This change adds openssh-client tools to run server-side SCP commands.

## Benefits of this PR and context:

Allow uses to run SCP commands

## How Has This Been Tested?

Running SCP commands against a running container process.

### CODE REVIEW

**Comment by thelamer** [comment]
I am not going to garuntee a merge as this might be outside of the intent of the container. 

But you need to keep packages in alphabetical order and make the same modifications to the `Dockerfile.aarch64` and the `Dockerfile.armhf` arm variants of this image.,

**Comment by vladimirvivien** [comment]
@thelamer thanks for (possibly) considering this. I made changes as you requested.

**Comment by aptalca** [comment]
Hi @vladimirvivien apologies for the wait.

We decided to add this as a docker mod, but had to figure out how to publish and host them first. There is now a mod for this at `linuxserver/mods:openssh-server-openssh-client`: https://github.com/linuxserver/docker-mods/tree/openssh-server-openssh-client

In your `openssh-server` container, set an environment variable `DOCKER_MODS=linuxserver/mods:openssh-server-openssh-client` and it will be installed during container start

**Comment by vladimirvivien** [comment]
👍

**Pull request closed without merging**
