### PR TITLE
Display SSH host public keys

### PR DESCRIPTION
**Pull request by BenjaminEHowe**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-openssh-server/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
This change displays the SSH host public keys every time the container starts.

## Benefits of this PR and context:
Outputting the public keys makes it easier for users to check them when connecting.

## How Has This Been Tested?
This is a relatively minor change. I have tested it on my laptop (Ubuntu 22.04 amd64, Docker 24.0.5) and it appears to work. Although I haven't had the opportunity to test the change on an `arm64` device I don't see any reason why the change wouldn't work there too.

### CODE REVIEW

**Comment by thespad** [comment]
Please use `/config/ssh_host_keys` rather than `/etc/ssh` as the latter is just a symlink to the persistent storage.

**Comment by thespad** [comment]
Thanks, I think I'm happy to approve this, can you just add an entry to the changelog in the readme-vars noting the change.

**Comment by aptalca** [comment]
One question. 

The PR description states `displays the SSH host public keys immediately after they are generated`. But it actually displays them on every container start.

Which is the behavior we want? Display only when they are generated or display them on every start?

**Comment by BenjaminEHowe** [comment]
> The PR description states `displays the SSH host public keys immediately after they are generated`. But it actually displays them on every container start.
> 
> Which is the behavior we want? Display only when they are generated or display them on every start?

Good spot. IMO the "cost" of displaying the keys is minimal, therefore it's worthwhile displaying them every time the container is started... but I'm happy to edit my code so it does what I said it would do 😄

**Comment by thespad** [comment]
Printing on every start probably makes more sense as you are likely to connect a new client at some point after first run so if you want a quick reference for the keys you want it there every time.

**Comment by BenjaminEHowe** [comment]
> Thanks, I think I'm happy to approve this, can you just add an entry to the changelog in the readme-vars noting the change.

Added an entry dated for tomorrow -- hopefully this is OK? (it's getting late-ish today in my TZ, I didn't want to assume that we'd get the change out today!)

**Comment by thespad** [comment]
Doesn't need to be spot on, just close enough that if someone has an issue as the result of a change they can see roughtly when it was made.

**Review by thespad — APPROVED** [review]

**Pull request merged**
