### PR TITLE
change home directory from default `/config` to $HOME_DIR

### PR DESCRIPTION
**Pull request by ddhp**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

 

------------------------------

We welcome all PR’s though this doesn’t guarantee it will be accepted.

## Description:

I am not sure if this PR makes sense, but so far if I login to the SSH server
```
ssh -i ~/.ssh/id_rsa linuxserver.io@localhost -p 2222
```
then `cat /etc/passwd` we can see the home directory for the user is `/config`

this PR would make it `/home/$USERNAME`

Please review when you have time and let me know your thoughts!

## Benefits of this PR and context:

Explained in Description

## How Has This Been Tested?

tested with local build and run:
```
$ docker build \
  --no-cache \
  --pull \
  -t linuxserver/openssh-server:local .

$ docker run -d \
  --name=openssh-server-local \
  -e PUBLIC_KEY="$(cat ~/.ssh/id_rsa.pub)" \
  -e SUDO_ACCESS=true \
  -e USER_NAME=my-user \
  -p 3333:2222 linuxserver/openssh-server:local
```
start SSH connection
```
ssh -i ~/.ssh/id_rsa my-user@localhost -p 3333
```
test commands:
```
:~$ cat /etc/passwd | grep /home/my-user
my-user:x:911:911::/home/my-user:/bin/bash

:~$ ls -al /home/my-user/
total 24
drwxr-xr-x 5 my-user my-user 4096 May 20 08:08 .
drwxr-xr-x 1 root    root    4096 May 20 08:08 ..
drwx------ 2 my-user my-user 4096 May 20 08:08 .ssh
drwxr-xr-x 3 my-user my-user 4096 May 20 08:08 logs
drwxr-xr-x 2 my-user my-user 4096 May 20 08:08 ssh_host_keys
-rw-r--r-- 1 my-user my-user    4 May 20 08:08 sshd.pid

:~$ ls -l /etc/ssh
lrwxrwxrwx 1 root root 27 May 20 08:08 /etc/ssh -> /home/my-user/ssh_host_keys

~$ ls -l ~/.ssh/authorized_keys 
-rw------- 1 my-user my-user 749 May 20 08:08 /home/my-user/.ssh/authorized_keys

~$ ls -l ~/logs/openssh/openssh.log
-rw------- 1 my-user my-user 309 May 20 08:08 /home/my-user/logs/openssh/openssh.log
```

## Source / References:

None

### CODE REVIEW

**Comment by aptalca** [comment]
What is the purpose?

You map that folder on the host to make it persistent anyway, and can map it to wherever on the host. Does it matter what it is called inside the container?

**Comment by ddhp** [comment]
Hey thanks for reviewing!

I am doing this is mainly for managing SSH authorizations. Public keys are looked up from the home folder, it's `/config` for the created user but it might be `/home/$USER_NAME` for users added later. If we can understand this is how the container setup it's fine but would it be better if we make it more consistent?

**Comment by aptalca** [comment]
I don't follow. What do you mean by users added later? Your PR would change the home for the first and only user.

This image is designed for a single user. If you create more users inside the container, they won't be persistent and will be lost after container recreation.

You can create multiple containers, one for each user with different (or same if you like) volume mappings and authorization options (sudo, password, etc.). Then map the config folders to different paths on the host so each user has their own container and their own persistent folder on host. They can connect through different ports dedicated to their container.

**Comment by ddhp** [comment]
Ah I see, if this image is designed for single user then this PR totally doesn't make any sense. Thanks for your thorough explanation.

**Pull request closed without merging**
